#ifndef _SMT_BOARD_
#define _SMT_BOARD_

#define TASK_LED_THREAD_PRIORITY RT_THREAD_PRIORITY_MAX - 3
#define TASK_IO_POLL_THREAD_PRIORITY RT_THREAD_PRIORITY_MAX - 2
#define TASK_SEND_THREAD_PRIORITY  RT_THREAD_PRIORITY_MAX - 1


#endif